CREATE TABLE "trading_setup"."TD05_Portfolio" (
  "TD05_Id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "TD01_Id" uuid NOT NULL,
  "CM02_Id" uuid NOT NULL,
  "TD03_Strategy" uuid,
  "TD05_Name" varchar(50) NOT NULL UNIQUE,
  "TD05_InitBalance" integer NOT NULL,
  "TD05_CurrentBalance" integer NOT NULL,
  "TD05_TotalConsecutiveWin" numeric NOT NULL DEFAULT 0,
  "TD05_TotalConsecutiveLoss" numeric NOT NULL DEFAULT 0,
  "TD05_TotalConsecutiveWinDay" numeric NOT NULL DEFAULT 0,
  "TD05_TotalConsecutiveLossDay" numeric NOT NULL DEFAULT 0,
  "TD05_SumTotalConsecutiveWin" numeric NOT NULL DEFAULT 0,
  "TD05_SumTotalConsecutiveLoss" numeric NOT NULL DEFAULT 0,
  "TD05_SumTotalConsecutiveWinDay" numeric NOT NULL DEFAULT 0,
  "TD05_SumTotalConsecutiveLossDay" numeric NOT NULL DEFAULT 0,
  "TD05_MaxProfitAmount" integer NOT NULL DEFAULT 0,
  "TD05_MaxLossAmount" integer NOT NULL DEFAULT 0,
  "TD05_AverageRiskRewardRatio" integer NOT NULL DEFAULT 0,
  "TD05_TotalTrade" numeric NOT NULL DEFAULT 0,
  "TD05_TotalWinTrade" numeric NOT NULL DEFAULT 0,
  "TD05_TotalLossTrade" numeric NOT NULL DEFAULT 0,
  "TD05_WinRatePercent" integer NOT NULL DEFAULT 0,
  "TD05_Description" varchar(255),
  "TD05_IsActive" boolean DEFAULT true NOT NULL,
  "TD05_CreatedBy" varchar(30) NOT NULL,
  "TD05_CreatedAt" timestamp NOT NULL DEFAULT NOW(),
  "TD05_ModifiedBy" varchar(30) NOT NULL,
  "TD05_ModifiedAt" timestamp NOT NULL DEFAULT NOW()
);
