export interface IPortfolioRow {
    TD05_Id: string;
    TD01_Id: string;
    CM02_Id: string;
    TD03_Strategy: string | null;
    TD05_Name: string;
    TD05_InitBalance: number;
    TD05_CurrentBalance: number;
    TD05_TotalConsecutiveWin: number;
    TD05_TotalConsecutiveLoss: number;
    TD05_TotalConsecutiveWinDay: number;
    TD05_TotalConsecutiveLossDay: number;
    TD05_SumTotalConsecutiveWin: number;
    TD05_SumTotalConsecutiveLoss: number;
    TD05_SumTotalConsecutiveWinDay: number;
    TD05_SumTotalConsecutiveLossDay: number;
    TD05_MaxProfitAmount: number;
    TD05_MaxLossAmount: number;
    TD05_AverageRiskRewardRatio: number;
    TD05_TotalTrade: number;
    TD05_TotalWinTrade: number;
    TD05_TotalLossTrade: number;
    TD05_WinRatePercent: number;
    TD05_TotalBreakEven: number;
    TD05_SumTotalBreakEven: number;
    CM05_Value: string | null;
    TD05_Description: string | null;
    TD05_IsActive: boolean;
    TD05_CreatedBy: string;
    TD05_CreatedAt: Date;
    TD05_ModifiedBy: string;
    TD05_ModifiedAt: Date;
    TD01_Name?: string;
    CM02_Name?: string;
    CM01_Name?: string;
    TD03_Name?: string | null;
}

export interface IPortfolio {
    id: string;
    projectId: string;
    projectName?: string;
    assetId: string;
    assetName?: string;
    assetTypeName?: string;
    strategyId: string | null;
    strategyName?: string | null;
    name: string;
    initBalance: number;
    currentBalance: number;
    totalConsecutiveWin: number;
    totalConsecutiveLoss: number;
    totalConsecutiveWinDay: number;
    totalConsecutiveLossDay: number;
    sumTotalConsecutiveWin: number;
    sumTotalConsecutiveLoss: number;
    sumTotalConsecutiveWinDay: number;
    sumTotalConsecutiveLossDay: number;
    maxProfitAmount: number;
    maxLossAmount: number;
    averageRiskRewardRatio: number;
    totalTrade: number;
    totalWinTrade: number;
    totalLossTrade: number;
    winRatePercent: number;
    totalBreakEven: number;
    sumTotalBreakEven: number;
    cm05Value: string | null;
    description: string | null;
    isActive: boolean;
    createdBy: string;
    createdAt: Date;
    modifiedBy: string;
    modifiedAt: Date;
}
